In [1]:
savings = 100

In [2]:
print(savings)

100


In [3]:
factor = 1.1

In [4]:
result = savings * factor ** 7

In [5]:
result

194.87171000000012

In [6]:
desc = "compound interest"

In [7]:
profitable = True

In [8]:
year1 = savings * factor

In [9]:
type(year1)

float

In [10]:
doubledesc = desc + desc

In [11]:
doubledesc

'compound interestcompound interest'

In [12]:
hall = 11.25

In [13]:
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

In [14]:
areas = ["hallway",hall,"Kitchen",kit,"living room",liv,"bedroom",bed,"bathroom",bath]

In [15]:
areas

['hallway',
 11.25,
 'Kitchen',
 18.0,
 'living room',
 20.0,
 'bedroom',
 10.75,
 'bathroom',
 9.5]

In [16]:
house = [["Hallway",hall],["Kitchen",kit],["living room",liv],["bedroom",bed],['bathroom',bath]]

In [17]:
house

[['Hallway', 11.25],
 ['Kitchen', 18.0],
 ['living room', 20.0],
 ['bedroom', 10.75],
 ['bathroom', 9.5]]

In [18]:
areas[1]

11.25

In [19]:
areas[-1]

9.5

In [20]:
areas[4]

'living room'

In [21]:
areas[5]

20.0

In [22]:
eat_sleep_area = kit + bed

In [23]:
eat_sleep_area

28.75

In [24]:
downstairs = areas[0:6]

In [25]:
downstairs

['hallway', 11.25, 'Kitchen', 18.0, 'living room', 20.0]

In [26]:
upstairs = areas[-4:]

In [27]:
upstairs

['bedroom', 10.75, 'bathroom', 9.5]

In [28]:
downstairs = areas[:6]

In [29]:
upstairs = areas[-4:]

In [30]:
downstairs

['hallway', 11.25, 'Kitchen', 18.0, 'living room', 20.0]

In [31]:
upstairs

['bedroom', 10.75, 'bathroom', 9.5]

In [32]:
areas[-1] = 10.50

In [33]:
areas

['hallway',
 11.25,
 'Kitchen',
 18.0,
 'living room',
 20.0,
 'bedroom',
 10.75,
 'bathroom',
 10.5]

In [34]:
areas[4]

'living room'

In [35]:
areas[4] = "chill zone"

In [36]:
areas

['hallway',
 11.25,
 'Kitchen',
 18.0,
 'chill zone',
 20.0,
 'bedroom',
 10.75,
 'bathroom',
 10.5]

In [37]:
areas_1 = areas + ["poolhouse",24.5]

In [38]:
areas_1

['hallway',
 11.25,
 'Kitchen',
 18.0,
 'chill zone',
 20.0,
 'bedroom',
 10.75,
 'bathroom',
 10.5,
 'poolhouse',
 24.5]

In [39]:
areas_2 = areas_1 + ["garage",15.45]

In [40]:
areas_2

['hallway',
 11.25,
 'Kitchen',
 18.0,
 'chill zone',
 20.0,
 'bedroom',
 10.75,
 'bathroom',
 10.5,
 'poolhouse',
 24.5,
 'garage',
 15.45]

In [41]:
areas_copy = areas[:]

In [42]:
areas_copy[0] = 5.0

In [43]:
areas_copy

[5.0,
 11.25,
 'Kitchen',
 18.0,
 'chill zone',
 20.0,
 'bedroom',
 10.75,
 'bathroom',
 10.5]

In [44]:
areas

['hallway',
 11.25,
 'Kitchen',
 18.0,
 'chill zone',
 20.0,
 'bedroom',
 10.75,
 'bathroom',
 10.5]

In [45]:
var1 = [1,2,3,4]

In [46]:
var2 = True

In [47]:
print(type(var1))

<class 'list'>


In [48]:
len(var1)

4

In [49]:
out2 = int(var2)

In [50]:
out2

1

In [51]:
first = [11.25,18.0,20.0]

In [52]:
second = [10.75,9.50]

In [53]:
full = first + second

In [54]:
full_sorted = sorted(full,reverse = True)

In [55]:
full_sorted

[20.0, 18.0, 11.25, 10.75, 9.5]

In [56]:
sister


NameError: name 'sister' is not defined

In [57]:
"sister".capitalize()

'Sister'

In [58]:
fam

NameError: name 'fam' is not defined

In [59]:
fam = ["supriya","komethagam","amppillai","arun"]

In [60]:
fam.append("mickey")

In [61]:
fam

['supriya', 'komethagam', 'amppillai', 'arun', 'mickey']

In [62]:
room = "poolhouse"

In [63]:
room_up = room.upper()

In [64]:
room

'poolhouse'

In [65]:
room_up

'POOLHOUSE'

In [66]:
room.count("o")

3

In [67]:
print(areas.index(20))

5


In [68]:
areas.count(20)

1

In [69]:
areas.append(24.5)

In [70]:
areas.append(15.45)

In [71]:
areas

['hallway',
 11.25,
 'Kitchen',
 18.0,
 'chill zone',
 20.0,
 'bedroom',
 10.75,
 'bathroom',
 10.5,
 24.5,
 15.45]

In [72]:
areas

['hallway',
 11.25,
 'Kitchen',
 18.0,
 'chill zone',
 20.0,
 'bedroom',
 10.75,
 'bathroom',
 10.5,
 24.5,
 15.45]

In [73]:
print(areas.reverse())

None


In [74]:
areas

[15.45,
 24.5,
 10.5,
 'bathroom',
 10.75,
 'bedroom',
 20.0,
 'chill zone',
 18.0,
 'Kitchen',
 11.25,
 'hallway']

In [75]:
import numpy as np

In [76]:
np.array([1,2,3])

array([1, 2, 3])

In [77]:
fam = ["supriya",23,"adf4etg",45,"dhwiijr",37]

In [78]:
fam_1 = fam + ["me",26]

In [79]:
np_fam = np.array(fam_1)

In [80]:
np_fam

array(['supriya', '23', 'adf4etg', '45', 'dhwiijr', '37', 'me', '26'], 
      dtype='<U7')

In [81]:
r = 0.43

In [82]:
c = 2 * math.pi * r

NameError: name 'math' is not defined

In [83]:
import math

In [84]:
c = 2 * math.pi * r

In [85]:
A = math.pi * r**2

In [86]:
c

2.701769682087222

In [87]:
A

0.5808804816487527

In [88]:
"circumference: " +  str(c)

'circumference: 2.701769682087222'

In [89]:
"Area: " + str(A)

'Area: 0.5808804816487527'

In [90]:
dist = r * radians(12)

NameError: name 'radians' is not defined

In [91]:
from math import radians

In [92]:
r = 192500

In [93]:
dist = r * radians(12)

In [94]:
dist

40317.10572106901

In [110]:
height = [1.73,1.68,1.71,1.89,1.79]

In [111]:
weight = [45.3,24.4,45.4,12.3,23.4,10.3]

In [112]:
np_height = np.array(height)

In [113]:
np_height

array([ 1.73,  1.68,  1.71,  1.89,  1.79])

In [114]:
np_weight = np.array(weight)

In [115]:
bmi = np_weight / np_height ** 2

ValueError: operands could not be broadcast together with shapes (6,) (5,) 

In [116]:
np_weight

array([ 45.3,  24.4,  45.4,  12.3,  23.4,  10.3])

In [117]:
bmi

NameError: name 'bmi' is not defined

In [118]:
baseball = [180,215,210,210,188,176,209,200]

In [119]:
np_baseball = np.array(baseball)

In [120]:
type(np_baseball)

numpy.ndarray

In [121]:
np_baseball

array([180, 215, 210, 210, 188, 176, 209, 200])

In [122]:
np_height

array([ 1.73,  1.68,  1.71,  1.89,  1.79])

In [125]:
np_height_m = np.array(height) * 0.0254

In [139]:
np_height_m

array([ 0.043942,  0.042672,  0.043434,  0.048006,  0.045466])

In [127]:
np_weight_kg = np.array(weight) * 0.453592

In [131]:
np_weight_kg

array([ 20.5477176,  11.0676448,  20.5930768,   5.5791816,  10.6140528,
         4.6719976])

In [135]:
bmi = (np_weight_kg) / (np_height_m ** 2)

ValueError: operands could not be broadcast together with shapes (6,) (5,) 

In [140]:
bmi = 20.5477176/0.43942 ** 2

In [141]:
bmi

106.41526939774786

np_weight

In [142]:
np_weight

array([ 45.3,  24.4,  45.4,  12.3,  23.4,  10.3])

In [143]:
np_weight[50]

IndexError: index 50 is out of bounds for axis 0 with size 6

In [144]:
np_height[100:111]

array([], dtype=float64)

In [145]:
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

In [146]:
np_baseball = np.array(baseball)

In [147]:
type(np_baseball)

numpy.ndarray

In [149]:
np_baseball.shape

(4, 2)

In [151]:
np_baseball[2,:]

array([ 210. ,   98.5])

In [152]:
np_weight = np_baseball[:,1]

In [153]:
np_weight

array([  78.4,  102.7,   98.5,   75.2])

In [157]:
np_height= np_baseball[:,0]

In [158]:
np_height

array([ 180.,  215.,  210.,  188.])

In [159]:
np.median(np_height)

199.0

In [160]:
stddev = np.std(np_baseball[:,0])

In [163]:
np.corrcoef(np_baseball[:,0],np_baseball[:,1])

array([[ 1.        ,  0.95865738],
       [ 0.95865738,  1.        ]])