In [1]:
"supriya" < "priya"

False

In [2]:
import numpy as np

In [3]:
my_house = np.array([18.0,20.0,10.75,9.50])

In [4]:
your_house = np.array([14.0,24.0,14.25,9.0])

In [5]:
my_house >= 18

array([ True,  True, False, False], dtype=bool)

In [6]:
my_house < your_house

array([False,  True,  True, False], dtype=bool)

In [7]:
my_kitchen  = 18.0

In [8]:
your_kitchen = 14.0

In [9]:
my_kitchen > 10 and my_kitchen < 18

False

In [10]:
my_kitchen < 14 or my_kitchen > 17

True

In [12]:
my_kitchen * 2 < 3 * your_kitchen

True

In [13]:
np.logical_or(my_house > 18.5,my_house < 10)

array([False,  True, False,  True], dtype=bool)

In [14]:
np.logical_and(my_house < 11, your_house < 11)

array([False, False, False,  True], dtype=bool)

In [15]:
z = 5
if z%2 == 0:
    print("even")
else:
    print("odd")

odd


In [20]:
room  ="kit"
area = 14.0

In [25]:
if room == "kit":
    print("looking around in the kitchen")
elif room == "bed":
    print("looking around in the bedroom")
else:
    print("looking around somewhere")

looking around in the kitchen


In [27]:
if area > 15:
    print("big place!")
elif area > 10:
    print("medium")
else:
    print("pretty small")

medium


In [49]:
import pandas as pd



In [50]:
names = ['united states','Australia','Japan','India',"Russia",'Morocco','Egypt']

In [51]:
dr = [True,False,False,False,True,True,True]

In [53]:
cpc = [809,731,588,18,200,70,45]

In [54]:
my_dict = {'country':names,'drives_right':dr,'cars_per_cpc':cpc}

In [55]:
cars = pd.DataFrame(my_dict)

In [58]:
dr = cars.loc[:,"drives_right"]

In [59]:
sel  = cars[dr]

In [60]:
sel

cars_per_cpc        country drives_right
0           809  united states         True
4           200         Russia         True
5            70        Morocco         True
6            45          Egypt         True

In [61]:
cpc = cars["cars_per_cpc"]

In [62]:
many_cars = cpc > 500

In [67]:
car_maniac  =cars[many_cars]

In [68]:
car_maniac

cars_per_cpc        country drives_right
0           809  united states         True
1           731      Australia        False
2           588          Japan        False

In [77]:
medium  =cars[np.logical_and(cars['cars_per_cpc'] > 100,cars['cars_per_cpc'] < 500)]

In [78]:
medium

cars_per_cpc country drives_right
4           200  Russia         True